-- Fix: room_study_heartbeat's room whitelist only allowed the "-1/-2/-3" variant of each
-- pomodoro room, but src/lib/rooms.ts's pomodoroVariants() generates 6 variants of 25-5-*,
-- 5 of 20-5-*, and 6 of 50-10-* (count = ceil((workMin+breakMin)/breakMin)). Any session in a
-- "-4"+ room hit `raise exception 'unknown_room'` on every heartbeat, silently swallowed by
-- useStudyXp.ts -- zero XP/coins credited, no visible error. Switch to a pattern match against
-- the slugBase prefixes so this can't drift out of sync with rooms.ts again.
-- Run in Supabase → SQL Editor (jednorazowo, po 0015), on both production and local.

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true)
returns table (xp integer, study_seconds integer, coins integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_elapsed integer;
  v_gain integer;
  v_is_timer boolean;
  v_divisor integer;
  v_coin_seconds integer;
  v_coin_divisor integer;
  v_coin_gain integer;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';
  v_divisor := case when v_is_timer then 3000 else 300 end;
  -- 1 coin per 60s in study rooms, 1 coin per 600s (0.1/min) in the Timer Room.
  v_coin_divisor := case when v_is_timer then 600 else 60 end;

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds, timer_coin_seconds into v_last, v_seconds, v_coin_seconds
    from public.profiles where id = auth.uid() for update;
  else
    select xp_heartbeat_at, study_seconds, coin_seconds into v_last, v_seconds, v_coin_seconds
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, or right after resuming from pause) only starts the
  -- clock — nothing to credit yet. Elapsed is capped a little above the 60s heartbeat interval
  -- so a backgrounded/stale tab that wakes up later can't award a windfall for the time it was
  -- away. A heartbeat sent while not running (timer paused) never credits elapsed time either.
  v_elapsed := case when v_last is null or not p_running then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;

  v_seconds := v_seconds + v_elapsed;
  v_gain := v_seconds / v_divisor;
  v_seconds := v_seconds % v_divisor;

  v_coin_seconds := v_coin_seconds + v_elapsed;
  v_coin_gain := v_coin_seconds / v_coin_divisor;
  v_coin_seconds := v_coin_seconds % v_coin_divisor;

  if v_is_timer then
    update public.profiles
    set xp = profiles.xp + v_gain,
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end,
        coins = profiles.coins + v_coin_gain,
        timer_coin_seconds = v_coin_seconds
    where id = auth.uid();

    return query select profiles.xp, profiles.timer_study_seconds, profiles.coins from public.profiles where id = auth.uid();
  else
    update public.profiles
    set xp = profiles.xp + v_gain,
        study_seconds = v_seconds,
        xp_heartbeat_at = now(),
        coins = profiles.coins + v_coin_gain,
        coin_seconds = v_coin_seconds
    where id = auth.uid();

    return query select profiles.xp, profiles.study_seconds, profiles.coins from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean) to authenticated;
