-- XP and coins become fractional (1 decimal place, normal rounding) instead of only paying out
-- once a whole unit is crossed. Previously the Timer Room's low rate (0.1 XP/5min, 0.1 coin/min)
-- meant `xp`/`coins` (integer) stayed at 0 until 50/10 minutes of accumulated time -- correct by
-- design, but the user wants partial credit visible after every ~1 minute heartbeat (see
-- src/lib/useStudyXp.ts's HEARTBEAT_MS) instead of waiting for a whole-unit threshold.
--
-- `study_seconds`/`timer_study_seconds` become uncapped running totals of elapsed presence time
-- (previously bucketed mod 300/3000 seconds, wrapping each time a whole XP paid out). xp/coins
-- are now derived fresh each heartbeat as round(total_seconds / rate_seconds, 1) rather than
-- incremented by a rounded-per-tick amount -- incrementing per tick would round the Timer Room's
-- ~0.02 XP/heartbeat down to 0.0 forever, since 1 decimal place can't represent that increment.
-- Deriving from the uncapped total avoids that trap and can't drift from rounding many small
-- increments over time.
--
-- coin_seconds/timer_coin_seconds are no longer needed: coins are now derived from the same
-- study_seconds/timer_study_seconds clock as xp, just with a different divisor.
-- Run in Supabase → SQL Editor (jednorazowo, po 0016), on both production and local.

alter table public.profiles
  alter column xp type numeric(12, 1) using round(xp::numeric, 1),
  alter column coins type numeric(12, 1) using round(coins::numeric, 1);

alter table public.profiles
  drop constraint if exists profiles_study_seconds_check,
  drop constraint if exists profiles_timer_study_seconds_check;

alter table public.profiles
  drop column if exists coin_seconds,
  drop column if exists timer_coin_seconds;

drop function if exists public.room_study_heartbeat(text, boolean);

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true)
returns table (xp double precision, study_seconds integer, coins double precision)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_elapsed integer;
  v_is_timer boolean;
  v_xp_divisor integer;
  v_coin_divisor integer;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';
  -- Study rooms: 1 XP / 5 min, 1 coin / 1 min. Timer Room: a tenth of both rates.
  v_xp_divisor := case when v_is_timer then 3000 else 300 end;
  v_coin_divisor := case when v_is_timer then 600 else 60 end;

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds into v_last, v_seconds
    from public.profiles where id = auth.uid() for update;
  else
    select xp_heartbeat_at, study_seconds into v_last, v_seconds
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, or right after resuming from pause) only starts the
  -- clock — nothing to credit yet. Elapsed is capped a little above the 60s heartbeat interval
  -- so a backgrounded/stale tab that wakes up later can't award a windfall for the time it was
  -- away. A heartbeat sent while not running (timer paused) never credits elapsed time either.
  v_elapsed := case when v_last is null or not p_running then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;

  v_seconds := v_seconds + v_elapsed;

  if v_is_timer then
    update public.profiles
    set xp = round(v_seconds::numeric / v_xp_divisor, 1),
        coins = round(v_seconds::numeric / v_coin_divisor, 1),
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.timer_study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  else
    update public.profiles
    set xp = round(v_seconds::numeric / v_xp_divisor, 1),
        coins = round(v_seconds::numeric / v_coin_divisor, 1),
        study_seconds = v_seconds,
        xp_heartbeat_at = now()
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean) to authenticated;
