-- Fix: room_study_heartbeat (0017_fractional_rewards.sql) fails with "column reference
-- study_seconds is ambiguous" for every non-Timer study room. `returns table (xp, study_seconds,
-- coins)` implicitly declares a plpgsql variable named `study_seconds` for the whole function, so
-- the unqualified `study_seconds` in the `select ... into` below collides with it. The Timer Room
-- branch never hit this because its column is named `timer_study_seconds`, not `study_seconds`.

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true)
returns table (xp double precision, study_seconds integer, coins double precision)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_elapsed integer;
  v_is_timer boolean;
  v_xp_divisor integer;
  v_coin_divisor integer;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';
  -- Study rooms: 1 XP / 5 min, 1 coin / 1 min. Timer Room: a tenth of both rates.
  v_xp_divisor := case when v_is_timer then 3000 else 300 end;
  v_coin_divisor := case when v_is_timer then 600 else 60 end;

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds into v_last, v_seconds
    from public.profiles where id = auth.uid() for update;
  else
    select profiles.xp_heartbeat_at, profiles.study_seconds into v_last, v_seconds
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, or right after resuming from pause) only starts the
  -- clock — nothing to credit yet. Elapsed is capped a little above the 60s heartbeat interval
  -- so a backgrounded/stale tab that wakes up later can't award a windfall for the time it was
  -- away. A heartbeat sent while not running (timer paused) never credits elapsed time either.
  v_elapsed := case when v_last is null or not p_running then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;

  v_seconds := v_seconds + v_elapsed;

  if v_is_timer then
    update public.profiles
    set xp = round(v_seconds::numeric / v_xp_divisor, 1),
        coins = round(v_seconds::numeric / v_coin_divisor, 1),
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.timer_study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  else
    update public.profiles
    set xp = round(v_seconds::numeric / v_xp_divisor, 1),
        coins = round(v_seconds::numeric / v_coin_divisor, 1),
        study_seconds = v_seconds,
        xp_heartbeat_at = now()
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean) to authenticated;
