-- Two bugs found while debugging 0021:
--
-- 1) xp/coins were derived from only ONE of the two seconds counters (study_seconds for room
--    heartbeats, timer_study_seconds for Timer Room heartbeats) and written to the SAME shared
--    `xp`/`coins` columns each time — so whichever path called last overwrote the other path's
--    contribution instead of adding to it. Fix: always derive xp/coins as the sum of both.
--
-- 2) Entering a room fires an immediate heartbeat (see src/lib/useStudyXp.ts), which credited
--    `now() - <user's last heartbeat, in ANY room>` — so walking into a room right after leaving
--    another one (or the lobby) granted a few free seconds of reward for nothing. Fix: a new
--    `p_reset` param (sent as true only for that first heartbeat of a mount) skips crediting
--    elapsed time and just syncs the clock, same as the existing "first heartbeat ever" case.
--
-- Signature changes (text, boolean) -> (text, boolean, boolean), so the old overload must be
-- dropped before creating the new one; CREATE OR REPLACE alone won't do it.

drop function if exists public.room_study_heartbeat(text, boolean);

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true, p_reset boolean default false)
returns table (xp double precision, study_seconds integer, coins double precision)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_other_seconds integer;
  v_elapsed integer;
  v_is_timer boolean;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds, profiles.study_seconds
      into v_last, v_seconds, v_other_seconds
    from public.profiles where id = auth.uid() for update;
  else
    select profiles.xp_heartbeat_at, profiles.study_seconds, timer_study_seconds
      into v_last, v_seconds, v_other_seconds
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, right after resuming from pause, or the first one of a
  -- fresh mount — see `p_reset` above) only starts the clock — nothing to credit yet. Elapsed is
  -- otherwise capped a little above the 60s heartbeat interval so a backgrounded/stale tab that
  -- wakes up later can't award a windfall for the time it was away. A heartbeat sent while not
  -- running (timer paused) never credits elapsed time either.
  v_elapsed := case when v_last is null or not p_running or p_reset then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;

  v_seconds := v_seconds + v_elapsed;

  if v_is_timer then
    update public.profiles
    set xp = round(v_other_seconds::numeric / 300, 1) + round(v_seconds::numeric / 3000, 1),
        coins = round(v_other_seconds::numeric / 60, 1) + round(v_seconds::numeric / 600, 1),
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.timer_study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  else
    update public.profiles
    set xp = round(v_seconds::numeric / 300, 1) + round(v_other_seconds::numeric / 3000, 1),
        coins = round(v_seconds::numeric / 60, 1) + round(v_other_seconds::numeric / 600, 1),
        study_seconds = v_seconds,
        xp_heartbeat_at = now()
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean, boolean) to authenticated;
