-- Bug (reported 2026-09-23): Shop showed a 0.0 copper coin balance for a player who had just
-- earned ~131 coins from pomodoro sessions.
--
-- Root cause: room_study_heartbeat (see 0022) recomputes xp/coins from scratch on every call as
-- round(study_seconds/…) + round(timer_study_seconds/…) and OVERWRITES the columns with that
-- value — including on the very first "p_reset" heartbeat of every room mount (see
-- src/lib/useStudyXp.ts), which credits no elapsed time but still runs the same UPDATE. Meanwhile
-- room_session_complete (0026, pomodoro lump-sum payout) and purchase_color_change/
-- purchase_cosmetic (0019/0027) add/subtract coins (and 0026 adds xp) directly on top of that same
-- column. None of those additions are reflected in study_seconds/timer_study_seconds, so the next
-- heartbeat — fired just by walking into any study room or the Timer Room — silently wipes them.
--
-- Fix: track the time-derived component in its own shadow columns (time_xp/time_coins, exactly
-- what the old formula produced) and apply only the *delta* of that formula to the real xp/coins
-- columns on each heartbeat, instead of overwriting them outright. Lump-sum grants and purchases
-- now survive a heartbeat because it only ever nudges xp/coins by the time actually earned since
-- the last heartbeat.
-- Run in Supabase → SQL Editor (jednorazowo, po 0027), on both production and local.

alter table public.profiles
  add column if not exists time_xp numeric(12, 1) not null default 0,
  add column if not exists time_coins numeric(12, 1) not null default 0;

-- Backfill: before room_session_complete/purchase_cosmetic existed, xp/coins were always exactly
-- what the time formula produced, so time_xp/time_coins start out equal to the current xp/coins —
-- this makes the very next heartbeat's delta 0 (or whatever real time has passed since), not a
-- retroactive correction of the already-broken balance.
update public.profiles set time_xp = xp, time_coins = coins;

drop function if exists public.room_study_heartbeat(text, boolean, boolean);

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true, p_reset boolean default false)
returns table (xp double precision, study_seconds integer, coins double precision)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_other_seconds integer;
  v_elapsed integer;
  v_is_timer boolean;
  v_old_time_xp numeric;
  v_old_time_coins numeric;
  v_new_time_xp numeric;
  v_new_time_coins numeric;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds, profiles.study_seconds, time_xp, time_coins
      into v_last, v_seconds, v_other_seconds, v_old_time_xp, v_old_time_coins
    from public.profiles where id = auth.uid() for update;
  else
    select profiles.xp_heartbeat_at, profiles.study_seconds, timer_study_seconds, time_xp, time_coins
      into v_last, v_seconds, v_other_seconds, v_old_time_xp, v_old_time_coins
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, right after resuming from pause, or the first one of a
  -- fresh mount — see `p_reset` above) only starts the clock — nothing to credit yet. Elapsed is
  -- otherwise capped a little above the 60s heartbeat interval so a backgrounded/stale tab that
  -- wakes up later can't award a windfall for the time it was away. A heartbeat sent while not
  -- running (timer paused) never credits elapsed time either.
  v_elapsed := case when v_last is null or not p_running or p_reset then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;

  v_seconds := v_seconds + v_elapsed;

  if v_is_timer then
    v_new_time_xp := round(v_other_seconds::numeric / 300, 1) + round(v_seconds::numeric / 3000, 1);
    v_new_time_coins := round(v_other_seconds::numeric / 60, 1) + round(v_seconds::numeric / 600, 1);

    update public.profiles
    set xp = xp + (v_new_time_xp - v_old_time_xp),
        coins = coins + (v_new_time_coins - v_old_time_coins),
        time_xp = v_new_time_xp,
        time_coins = v_new_time_coins,
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.timer_study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  else
    v_new_time_xp := round(v_seconds::numeric / 300, 1) + round(v_other_seconds::numeric / 3000, 1);
    v_new_time_coins := round(v_seconds::numeric / 60, 1) + round(v_other_seconds::numeric / 600, 1);

    update public.profiles
    set xp = xp + (v_new_time_xp - v_old_time_xp),
        coins = coins + (v_new_time_coins - v_old_time_coins),
        time_xp = v_new_time_xp,
        time_coins = v_new_time_coins,
        study_seconds = v_seconds,
        xp_heartbeat_at = now()
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean, boolean) to authenticated;
