-- STU-19: "why do I get +1.1 coin per minute instead of +1?"
--
-- Root cause: room_study_heartbeat (see 0028) credits the *actual* wall-clock gap since the last
-- heartbeat, capped at 75s. src/lib/useStudyXp.ts fires a heartbeat every HEARTBEAT_MS = 60_000ms,
-- but normal event-loop/network jitter routinely pushes the real gap to ~63-68s, so a "1 minute"
-- tick often credits round(66/60, 1) = 1.1 coins instead of exactly 1.
--
-- Fix: snap the elapsed gap to exactly 60s whenever it's within a jitter window around the
-- expected 60s heartbeat tick (45-75s), so a normal, on-time heartbeat always credits exactly
-- 1 coin / 1/5 XP. Gaps outside that window (paused/backgrounded/reconnected) are real, unusual
-- gaps and keep being credited as-is (still capped at 75s, unchanged).
-- Run in Supabase → SQL Editor (jednorazowo, po 0033), on both production and local.

create or replace function public.room_study_heartbeat(p_room text, p_running boolean default true, p_reset boolean default false)
returns table (xp double precision, study_seconds integer, coins double precision)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
  v_seconds integer;
  v_other_seconds integer;
  v_raw_elapsed integer;
  v_elapsed integer;
  v_is_timer boolean;
  v_old_time_xp numeric;
  v_old_time_coins numeric;
  v_new_time_xp numeric;
  v_new_time_coins numeric;
begin
  -- Must match the real room slugs generated by pomodoroVariants() in src/lib/rooms.ts
  -- ("<base>-<n>" for n = 1..count) plus the Timer Room's fixed "timer" slug.
  if p_room != 'timer' and p_room !~ '^(25-5|20-5|50-10)-[1-9][0-9]*$' then
    raise exception 'unknown_room' using errcode = 'P0001';
  end if;

  v_is_timer := p_room = 'timer';

  if v_is_timer then
    select timer_heartbeat_at, timer_study_seconds, profiles.study_seconds, time_xp, time_coins
      into v_last, v_seconds, v_other_seconds, v_old_time_xp, v_old_time_coins
    from public.profiles where id = auth.uid() for update;
  else
    select profiles.xp_heartbeat_at, profiles.study_seconds, timer_study_seconds, time_xp, time_coins
      into v_last, v_seconds, v_other_seconds, v_old_time_xp, v_old_time_coins
    from public.profiles where id = auth.uid() for update;
  end if;

  if not found then
    raise exception 'no_profile' using errcode = 'P0001';
  end if;

  -- First heartbeat (ever, after a gap, right after resuming from pause, or the first one of a
  -- fresh mount — see `p_reset` above) only starts the clock — nothing to credit yet. Elapsed is
  -- otherwise capped a little above the 60s heartbeat interval so a backgrounded/stale tab that
  -- wakes up later can't award a windfall for the time it was away. A heartbeat sent while not
  -- running (timer paused) never credits elapsed time either.
  v_raw_elapsed := case when v_last is null or not p_running or p_reset then 0
    else least(greatest(extract(epoch from (now() - v_last))::integer, 0), 75) end;
  -- Snap normal-jitter gaps (see doc above) to exactly 60s so an on-time heartbeat always credits
  -- a whole coin/fifth-of-XP instead of a jitter-sized fraction of one.
  v_elapsed := case when v_raw_elapsed between 45 and 75 then 60 else v_raw_elapsed end;

  v_seconds := v_seconds + v_elapsed;

  if v_is_timer then
    v_new_time_xp := round(v_other_seconds::numeric / 300, 1) + round(v_seconds::numeric / 3000, 1);
    v_new_time_coins := round(v_other_seconds::numeric / 60, 1) + round(v_seconds::numeric / 600, 1);

    update public.profiles
    set xp = xp + (v_new_time_xp - v_old_time_xp),
        coins = coins + (v_new_time_coins - v_old_time_coins),
        time_xp = v_new_time_xp,
        time_coins = v_new_time_coins,
        timer_study_seconds = v_seconds,
        timer_heartbeat_at = case when p_running then now() else null end
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.timer_study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  else
    v_new_time_xp := round(v_seconds::numeric / 300, 1) + round(v_other_seconds::numeric / 3000, 1);
    v_new_time_coins := round(v_seconds::numeric / 60, 1) + round(v_other_seconds::numeric / 600, 1);

    update public.profiles
    set xp = xp + (v_new_time_xp - v_old_time_xp),
        coins = coins + (v_new_time_coins - v_old_time_coins),
        time_xp = v_new_time_xp,
        time_coins = v_new_time_coins,
        study_seconds = v_seconds,
        xp_heartbeat_at = now()
    where id = auth.uid();

    return query
      select profiles.xp::double precision, profiles.study_seconds, profiles.coins::double precision
      from public.profiles where id = auth.uid();
  end if;
end;
$$;

grant execute on function public.room_study_heartbeat(text, boolean, boolean) to authenticated;
